apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: bridge.network.kubevirt.io/br-vlan251
    labels:
      app.kubernetes.io/instance: vms
  name: vlan251-bridge 
  namespace: dell-heroes 
spec:
  config: '{"name":"labnet","type":"bridge","cniVersion":"0.3.1","bridge":"br-vlan251","macspoofchk":true,"ipam":{},"preserveDefaultVlan":false}'


